### ISSUE TITLE
Trysil for Delphi CE

### ISSUE THREAD

**Issue by rareMaxim** [davidlastrucci/Trysil#3]
When compile Trysil in Delphi CE - we can get error: 
`[dcc32 Fatal Error] Trysil.Data.FireDAC.SqlServer.pas(21): F2613 Unit 'FireDAC.Phys.MSSQL' not found.`

Module _FireDAC.Phys.MSSQL_ not used in _Trysil.Data.FireDAC.SqlServer.pas_. 

Solutuon: Delete unit _FireDAC.Phys.MSSQL_ in _Trysil.Data.FireDAC.SqlServer.pas_.

**Comment by davidlastrucci** [comment]
**Trysil** is written with the **Delphi Enterprise**.

You can also use it with Delphi Professional or CE, but you can only use Trysil with **SQLite**.

Do not remove FireDAC.Phys.MSSQL from Trysil.Data.FireDAC.SqlServer, and do not remove FireDAC.Phys.IBBase and FireDAC.Phys.FB from Trysil.Data.FireDAC.FirebirdSQL.

FireDAC.Phys.MSSQL, FireDAC.Phys.IBBase and FireDAC.Phys.FB are not part of the professional and the CE versions.

Remove the following units from the project:
- Trysil.Data.SqlSyntax.SqlServer
- Trysil.Data.SqlSyntax.FirebirdSQL
- Trysil.Data.FireDAC.SqlServer
- Trysil.Data.FireDAC.FirebirdSQL

HTH,
David
