### ISSUE TITLE
Suggestion: SQLite3 concurrency

### ISSUE THREAD

**Issue by Olray** [davidlastrucci/Trysil#7]
Right now Trysil configures the SQLite3 FireDAC database driver to lock a database exclusively by omitting the configuration parameter 'LockingMode=Normal'.

Can I suggest to add right before line 157 in Trysil.Data.FireDAC.SQLite:
```
    LParameters.Add('LockingMode=Normal');
```

The full class method RegisterConnection then is:
```
class procedure TTSQLiteConnection.RegisterConnection(
  const AName: String;
  const AUsername: String;
  const APassword: String;
  const ADatabaseName: String);
var
  LParameters: TStrings;
begin
  LParameters := TStringList.Create;
  try
    LParameters.Add(Format('Database=%s', [ADatabaseName]));
    if not AUsername.IsEmpty then
    begin
      LParameters.Add(Format('User_Name=%s', [AUserName]));
      LParameters.Add(Format('Password=%s', [APassword]));
    end;
    LParameters.Add('LockingMode=Normal');

    RegisterConnection(AName, LParameters);
  finally
    LParameters.Free;
  end;
end;
```

**Comment by davidlastrucci** [comment]
Solved, thank you for reporting.

**Comment by Olray** [comment]
If you omit the rowid (or the other autoincrement field) in the SQL INSERT command you can retrieve the real ROWID assigned by SQLite3 by calling sqlite3_last_insert_rowid() which is defined in System.Sqlite.pas and then update the entity accordingly. Until then the autoincrement value could stay at zero.
Downside: You can only insert rows one by one.
At least this is how the popular Doctrine seems to work. This could be a possible solution.

**Comment by davidlastrucci** [comment]
Thanks, I will review the documentation and try to make the change.

**Comment by Olray** [comment]
That's not a simple task. While it's easy to initialize the PODO with 0 as an ID and omit the ID field on updates (which only needs a few more methods in .\Trysil\Data\SqlSyntax\Trysil.Data.SqlSyntax.SQLite.pas and a change in TTSQLiteSequenceSyntax.GetSequenceSyntax), the PODO will get out of sync after inserting. Generally speaking, this currently happens with all AUTOINCREMENT fields in a table. And I'm _almost_ sure this is a problem (or not) with other DBMS as well. After inserting, the PODO must be synced with the values of the autoincrement fields as determined by the DBMS.

I'm a little embarrassed to admit it, but after about two hours, I still couldn't find that part of the code. Trysil's architecture is just so advanced.

**Comment by davidlastrucci** [comment]
AUTOINCREMENTs are not handled by Trysil, the ID is calculated before doing INSERT. For this reason, "**last_insert_rowid()**" requires significant changes in the flow of TTProvider and TTResolver.

I suggest a different solution.

Create a table __TTSequences on the database:
```
CREATE TABLE IF NOT EXISTS __TTSequences (
    Sequence TEXT NOT NULL PRIMARY KEY,
    Value INTEGER NOT NULL DEFAULT 0
  );
```

To calculate the new ID, we can use the following syntaxes within a transaction:
```
INSERT OR IGNORE INTO __TTSequences (Sequence, Value)
SELECT 'Sequence', IFNULL(MAX(ROWID), 0) FROM Sequence;
```
```
UPDATE __TTSequences SET Value = Value + 1 WHERE Sequence = 'Sequence';
```
```
SELECT Value FROM __TTSequences WHERE Sequence = 'Sequence';
```

We can execute the three SQL statements directly from the SQLite connection (TTSQLiteConnection) by overriding the GetSequenceID method:

```
public
  function GetSequenceID(const ATableMap: TTTableMap): TTPrimaryKey; override;
```

Do you think it could work as a solution?

D.

**Comment by davidlastrucci** [comment]
I created a branch '**sqlite_concurrency**' with the changes previously proposed.

I only modified the following units:

- Data\SqlSyntax\Trysil.Data.SqlSyntax.SQLite.pas
- Data\FireDAC\Trysil.Data.FireDAC.SQLite.pas

**Comment by Olray** [comment]
This change will allow to create a bunch of objects with TTContext.CreateEntity() and insert them in a loop at a later time. But this is not a concurrency issue.

> Do you think it could work as a solution?

That idea looks very promising, but I believe the problem with precalculated primary keys is not a SqLite issue but also applies to other databases as well.

If there are any other apps writing to the database that aren't compiled with a Trysil version following this patch or are not using Trysil at all will not be aware of the agreement. They will most likely insert with "SET ID= MAX(ID)+1" which will then create an occupied record that will crash the insert process from Trysil unless you update __TTSequences prior to every insert.

A DBMS transaction commit only checks if the values can be stored correctly and without error, it doesn't check the values for correctness - and how could it.

If the other databases (Firebird, Postgre, SQL Server) are having the same issue it's worth tweaking with the architecture. In this case I suggest the following:
* Creating a PODO with TTContext.CreateEntity() should set the TTPrimaryKey to zero. (Result := 'SELECT 0'; in TTSQLiteSequenceSyntax.GetSequenceSyntax)
* On INSERT the TTPrimary key is omitted from the insert statement and the DBMS does it's job. (Override TTInsertSyntax for SQLite)
* Right after inserting the record into the database table, there must be a system for every DBMS to retrieve the actual TTPrimaryKey value. For SQLite3 there is sqlite3_last_insert_rowid() but other DBMS will have a similar function call (see [1] below)
* The PODO should be updated with the new primary key, so later calls that update the row are successful.

[1]: This [might be helpful](https://hightouch.com/sql-dictionary/sql-last_insert_id)

**Comment by davidlastrucci** [comment]
Calculating the primary key after insertion leads to problems with 1-to-N relationships. If I have an Orders table and an OrderItems table, OrderItems will contain the OrderID column that must be updated after the insertion into the Orders table. Also consider that the insertion of the Order and its Items should happen within a transaction.

It is much better to have the order ID when I go to create a new entity of type TOrder.

The other databases do not have the same problem: Firebird, PostgreSQL, and SQL Server have SEQUENCEs.

Support for SQLite arises from the need to use it on a mobile device.

**Comment by Olray** [comment]
I see your point. You cannot create and insert an object graph into the database if the primary id of the parent object is unknown. It would require to insert the parent object first and then work with the updated primary key thus forcing all users of Trysil to rewrite part of their business logic. And when insertion fails, you have a bogus parent object in that table.

Also on mobile devices the app owns the database file. There are no external apps accessing it.

You're 100% right and your solution will solve the problem. Well done.
